openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Notification Services API'
  description: Notification Services API

servers:
  - url: https://www.cusports.com/api

paths:
    /notifications:
        get:
          description: Returns a list of all the types of notifications
          responses:
            '200':
              description: Retrieved the list of all notifications types
              content:
                application/json:
                    schema:
                        type: array
                        items:
                            
                            $ref: "#/components/schemas/Notification"

            '400':
                description: Did not reach server successfully
                $ref: "#/components/responses/400Error"
            '500':
                $ref: "#/components/responses/500Error"
        post:
            description: Notifications table changed
            responses:
              '200':
                description: Notifications table successfully changed
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/TableStructure"
                            
              '400':
                description: Did not reach server successfully
                $ref: "#/components/responses/400Error"
              '500':
                $ref: "#/components/responses/500Error"

    /notifications/id/{id}:
        parameters:
          - name: id
            description: User ID to retrieve notifications for
            in: path
            required: true
            schema:
                type: string
          - name: notype
            description: Notification type to filter by
            in: query
            required: true
            schema:
                type: string
            
        get:
            description: Returns notifications for a specific user and type
            responses:
              '200':
                description: Notifications retrieved
                content:
                  application/json:
                    schema:
                        type: object
                        properties:
                          message:
                            type: string
                          notifications:
                            type: array
                            items:
                              $ref: "#/components/schemas/Notification"

              '400':
                description: Did not reach server successfully
                $ref: "#/components/responses/400Error"
              '404':
                description: No notifications found
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        error:
                          type: string
              '500':
                $ref: "#/components/responses/500Error"

    /Notification_Cat:
        post:
            description: Creates a new notification type
            responses:
              '200':
                description: Notification type successfully created
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Notification"
components:
     
    responses:
        400Error:
          description: Invalid Client Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: The client request was invalid
                    type: string
        500Error:
          description: Unexpected Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: The server has encountered an error
                    type: string
    schemas:
        Notification:
            description: The format of each notification
            type: object
            required:
              - message
            properties: 
                message:
                    type: string
        
        TableStructure:
            description: The format of each notification
            type: object
            required:
              - notificationId
              - id
              - notype
            properties: 
                notificationId:
                    type: string
                id:
                    type: integer
                notype:
                    type: string